#!/bin/bash

set -ex

juju-log "Polling for database setup and updated schema"
. /opt/canonical/landscape/scripts/landscape-env.sh
while ! schema_check; do
    juju-log "Schema still out of date."
    sleep 5
done;

lsctl restart

exit 0
