#!/bin/bash -e
# Needs to be run as a user who can sudo.  d'oh!
# It will ask your password a lot.

# Add the juju stable ppa, install amulet deps
sudo add-apt-repository -y ppa:juju/stable
sudo apt-get update
sudo apt-get -y install python3 juju-deployer amulet juju-core charm-tools

# Install Amulet from Trunk
#dir=$(mktemp -d)
#cd $dir
#git clone https://github.com/dpb1/amulet.git
#cd amulet
#git checkout make-non-interactive
#make sysdeps </dev/null
#sudo make install

# Install charm-tools from trunk -- remove asap
# https://bugs.launchpad.net/charm-tools/+bug/1271803
cd $dir
bzr branch lp:~davidpbritton/charm-tools/fix-test-env-1271745/ charm-tools
cd charm-tools
sudo python ./setup.py install
sudo rm -rf $dir
