#!/usr/bin/python2.7
"""
Write out a 'translated' configuration file.  That is:

  - put everything in one section
  - resolve 'include-*://' style links
  - name the yaml section after the current 'JUJU_ENV'

This is to workaround some amulet/deployer quirks.  It's in a file
since deployer libs are py2, and amulet is py3
"""

import os
import subprocess
from base64 import b64encode
from deployer.config import ConfigStack
from deployer.utils import resolve_include
import yaml
import argparse
import tempfile


def _resolve_include(value, base_dir):
    """
    resolve include-*:// style links in the way that
    juju-deployer does.  I cut and paste this code for now
    since it was a bit burried in a method.  The goal is
    to move this into amulet, I really don't want to maintain
    this here.
    """
    for include_type in ["file", "base64"]:
        if (not isinstance(value, str)
            or not value.startswith(
                "include-%s://" % include_type)):
            continue
        _, fname = value.split("://", 1)
        include_path = resolve_include(fname, [base_dir])
        with open(include_path) as fh:
            result = fh.read().strip()
            if include_type == "base64":
                result = b64encode(result)
            return result
    return value


def load_deployer_config(yaml_file, deployer_target="landscape", extra=None):
    """
    Load a deployer config, resolving all deployer indirections.

    The resulting structure will be a single-stanza, named after
    the current juju environment.  i.e., all 'inherit' directives
    will also be resolved.  This file would be portable and could be
    pasted to someone else for debugging.

    @param extra Extra yaml to be fed to deployer in a separate file
    """
    config_dir = os.path.dirname(yaml_file)
    files = [yaml_file]
    if extra:
        (handle, filename) = tempfile.mkstemp()
        with os.fdopen(handle, 'w') as f:
            f.write(extra)
        files.append(filename)

    config = ConfigStack(files)
    config.load()
    deployment = config.get(deployer_target)
    data = deployment.data
    os.unlink(filename)

    if "relations" not in data:
        data["relations"] = {}

    for service_name, service in data["services"].iteritems():
        if "options" in service:
            for key, value in service["options"].items():
                service["options"][key] = _resolve_include(value, config_dir)

    # FIXME: This is only needed since amulet switches your environment
    #        if you pass in a config.  There are ways to break this
    #        parsing (like including a quote in your environment name).
    output = subprocess.check_output(['juju', 'env']).strip()
    # Current environment: "andreas-canonistack2" (from JUJU_ENV)
    # <= Juju 1.16
    if output.startswith("Current environment: "):
        environment_name = output.split()[2].strip('"')
    else:
        environment_name = output
    return {environment_name: data}


def get_options():
    """Parse check and retrieve arguments and options."""
    description = "Generate a fully-formed juju-deployer file"
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("config_file",
                        metavar='CONFIG_FILE', help='Config file to base on')
    parser.add_argument(
        "-r", "--repository-url",
        metavar="REPO_URL",
        dest="repository_url",
        help="URL of the LDS repository to use. Use this to also "
        "implicitly select which LDS version you want.")
    parser.add_argument(
        "-t", "--deployer-target",
        metavar='TARGET', dest="deployer_target", default="landscape",
        help="Deployer target to extract and use for testing")
    options = parser.parse_args()
    return options


def main():
    options = get_options()
    # break the modeline print line so it isn't interpreted here
    print "# Vim seems to have a cow with the long yaml lines, hack for now"
    print "# See: https://stackoverflow.com/questions/20663169"
    print "# vim" + ":syntax=off"
    print "# you need set modeline for this to work"

    # Create an extra section '_extra_', which inherits the user-specified
    # deployer_target.  Use this section when generating our new config file
    # as it will allow us to specify extra things like overrides.
    extra = {"_extra_": {
        "inherits": options.deployer_target}}
    if options.repository_url:
        extra["_extra_"]["overrides"] = {"repository": options.repository_url}
    config = load_deployer_config(
        options.config_file, "_extra_", yaml.dump(extra))
    print yaml.dump(config, default_flow_style=False)


if __name__ == '__main__':
    main()
