#!/bin/bash -e
# Needs to be run as a user who can sudo.  d'oh!
# It will ask your password a lot.

# Install add-apt-repository (packaging differs across releases).
sudo apt-get -y install python-software-properties

# Add the juju stable ppa, install charm-tools (juju-test plugin) and other deps
sudo add-apt-repository -y ppa:juju/stable
sudo apt-get update
sudo apt-get -y install juju-deployer juju-core charm-tools python3 \
    python3-yaml curl python3-zope.testrunner \
    python3-amulet python3-fixtures python3-jinja2 python3-fixtures\
    python3-psutil python3-twisted python3-flake8

sudo apt-get -y install python-fixtures python-six python-yaml dpkg-dev \
    pbuilder dh-make python-jinja2 python-psutil flake8
