#!/usr/bin/python
import sys
from ConfigParser import RawConfigParser
from subprocess import check_output

import os
sys.path.insert(0, os.path.dirname(__file__))
import common

password = check_output(["relation-get", "password"]).strip()
host = check_output(["relation-get", "hostname"]).strip()

common.juju_log("Using AMPQ server at %s" % host)

if password == "":
    sys.exit(0)

config_file = "/etc/landscape/service.conf"

parser = RawConfigParser()
parser.read([config_file])

parser.set("broker", "password", password)
parser.set("broker", "host", host)
parser.set("broker", "user", "landscape")

with open(config_file, "w+") as output_file:
    parser.write(output_file)
