#!/bin/bash -xe

ROOT="$( cd "$( dirname "$0" )" && pwd )"

LS_LICENSE_FILE=`config-get license-file`
LICENSE_FILE_DEST=/etc/landscape/license.txt
LICENSE_FILE_RE='^`(.*)`$'
PUBLIC=`unit-get public-address`
SERVICES=$(config-get services)

# Provides $DEFAULT_VAR map
source $ROOT/services.sh

# For now, this will just enable http
setup_apache() {
    a2enmod rewrite
    a2enmod proxy_http
    a2enmod ssl
    a2enmod headers
    a2enmod expires
    a2dissite default
    cp $ROOT/conf/landscape-http /etc/apache2/sites-available/landscape
    sed -e "s/@hostname@/$PUBLIC/" -i /etc/apache2/sites-available/landscape
    a2ensite landscape
    service apache2 restart
}

enable_services() {
    juju-log "Selected services: $SERVICES"
    for i in $SERVICES; do
        juju-log "Enabling: $i"
        if [ $i == "static" ]; then
            setup_apache
        else
            var=${DEFAULT_VAR[$i]}
            sed -i "s/${var}=.*/${var}=\"yes\"/g" /etc/default/landscape-server
        fi
    done
}

install_license() {
    [ -z "$LS_LICENSE_FILE" ] && return
    if [[ $LS_LICENSE_FILE =~ $LICENSE_FILE_RE ]]; then
        LS_LICENSE_FILE=$(${BASH_REMATCH[1]})
    fi
    echo "$LS_LICENSE_FILE" > $LICENSE_FILE_DEST
}

# Put the license file in place.
install_license

# Enable all services that the were requested in the config
enable_services

# Restart landscape services
lsctl restart || /bin/true

exit 0
