#!/bin/bash -xe

ROOT="$( cd "$( dirname "$0" )" && pwd )"

LS_LICENSE_FILE=`config-get license-file`
LICENSE_FILE_DEST=/etc/landscape/license.txt
LICENSE_FILE_RE='^(http://|https://).*$'
PUBLIC=`unit-get public-address`
SERVICES=$(config-get services)

# Definition of available services in landscape, and mapping to the 
# variable in /etc/default/landcape
unset DEFAULT_VAR
declare -A DEFAULT_VAR
DEFAULT_VAR=(
    [appserver]="RUN_APPSERVER"
    [msgserver]="RUN_MSGSERVER"
    [pingserver]="RUN_PINGSERVER"
    [combo-loader]="RUN_COMBO_LOADER"
    [async-frontend]="RUN_ASYNC_FRONTEND"
    [apiserver]="RUN_APISERVER"
    [package-upload]="RUN_PACKAGEUPLOADSERVER"
    [jobhandler]="RUN_JOBHANDLER"
    [package-search]="RUN_PACKAGESEARCH"
)

# For now, this will just enable http
setup_apache() {
    a2enmod rewrite
    a2enmod proxy_http
    a2enmod ssl
    a2enmod headers
    a2enmod expires
    a2dissite default
    cp $ROOT/conf/landscape-http /etc/apache2/sites-available/landscape
    sed -e "s/@hostname@/$PUBLIC/" -i /etc/apache2/sites-available/landscape
    a2ensite landscape
    service apache2 restart
}

enable_services() {
    juju-log "Selected services: $SERVICES"
    for i in $SERVICES; do
        juju-log "Enabling: $i"
        if [ $i == "static" ]; then
            setup_apache
        else
            var=${DEFAULT_VAR[$i]}
            sed -i "s/${var}=.*/${var}=\"yes\"/g" /etc/default/landscape-server
        fi
    done
}

install_license() {
    [ -z "$LS_LICENSE_FILE" ] && return
    if [[ $LS_LICENSE_FILE =~ $LICENSE_FILE_RE ]]; then
        LS_LICENSE_FILE=$(wget --quiet -O - $LS_LICENSE_FILE)
    fi
    echo "$LS_LICENSE_FILE" > $LICENSE_FILE_DEST
}

# Put the license file in place.
install_license

# Enable all services that the were requested in the config
enable_services

# Restart landscape services
lsctl restart || /bin/true

exit 0
