#!/usr/bin/python

import sys
import os
import common
from subprocess import check_output
from ConfigParser import RawConfigParser

sys.path.insert(0, os.path.dirname(__file__))

common.set_host("account-1")
common.set_host("knowledge")
common.set_host("main")
common.set_host("package")
common.set_host("resource-1")
common.set_host("session")

host = check_output(["relation-get", "host"]).strip()
user = "landscape"
password = "landscape"
touch_file = "/var/tmp/landscape-msgserver-postgresql-done"

if host:
    config_file = "/etc/landscape/service.conf"

    parser = RawConfigParser()
    parser.read([config_file])

    parser.set("stores", "host", host)
    parser.set("stores", "port", "5432")
    parser.set("stores", "user", user)
    parser.set("stores", "password", password)

    with open(config_file, "w+") as output_file:
        parser.write(output_file)
