#!/usr/bin/python

import sys
import os
#import common
from subprocess import check_output
from ConfigParser import RawConfigParser

HOOKS = os.path.dirname(__file__)
sys.path.insert(0, HOOKS)

host = check_output(["relation-get", "host"]).strip()
user = "landscape"
password = "landscape"
touch_file = "/var/tmp/landscape-msgserver-postgresql-done"

if host:
    config_file = "/etc/landscape/service.conf"

    parser = RawConfigParser()
    parser.read([config_file])

    parser.set("stores", "host", host)
    parser.set("stores", "port", "5432")
    parser.set("stores", "user", user)
    parser.set("stores", "password", password)
    parser.set("schema", "store_user", user)
    parser.set("schema", "store_password", password)
    parser.set("schema", "host", host)

    with open(config_file, "w+") as output_file:
        parser.write(output_file)

    check_output([os.path.join(HOOKS, "start-services")])
