#!/bin/bash

set -x

export LC_ALL=C

LS_PPA=`config-get repository`

LS_PACKAGE="landscape-server_*.tar.gz"

SOURCES_FILE=/etc/apt/sources.list.d/landscape-devel-team.list
CODENAME=$(cat /etc/lsb-release | grep CODENAME | sed 's/.*=//')

die() {
    STATUS=$?
    echo "ERROR: $1"
    exit $STATUS 
}

setup_local_repo () {
    # If deb files are in place in the charm directory, setup a local
    # repository for installation

    ls $LS_PACKAGE || return;

    TMP=$(mktemp -d)
    cp -f $LS_PACKAGE $TMP

    PWD=$(pwd)

    # stage the source TGZ
    cd $TMP
    tar --strip=1 -xf $LS_PACKAGE
    ver=$(dpkg-parsechangelog|grep ^Version:|cut -d ' ' -f 2)
    dch -v 9999:$ver development --distribution $(lsb_release -cs)

    # Actually build the package.
    dpkg-buildpackage -us -uc

    # Stage the file:// based apt repository
    mv ../*.deb .
    dpkg-scanpackages -m . /dev/null > Packages
    cat Packages | bzip2 -9 > Packages.bz2
    cat Packages | gzip -9 > Packages.gz
    dpkg-scansources . > Sources
    cat Sources | bzip2 -9 > Sources.bz2
    cat Sources | gzip -9 > Sources.gz
    apt-ftparchive release . > Release

    # Add myh repository to apt
    add_apt_sources "deb file://$TMP/ ./"

    cd $PWD
}


get_private_ip () {
    # Make sure that we use the resolvable private address
    # dig deals with both hostnames and ip addresses in a nice
    # way - this has been tested in local and ec2 providers
    # with ec2 and openstack
    dig +short `unit-get private-address`
}

install_landscape() {
    apt_get update;
    apt_get install landscape-server
}

# $1 - optional additional source line to add
add_apt_sources() {
    cat > $SOURCES_FILE <<-EOMSG
deb ${LS_PPA} ${CODENAME} main
$1
EOMSG
    chmod go+r $SOURCES_FILE
    apt-key adv --keyserver keyserver.ubuntu.com --recv-key D394F4BC
    apt-key adv --keyserver keyserver.ubuntu.com --recv-key 4652B4E6
}

function apt_get() {
    DEBIAN_FRONTEND=noninteractive apt-get \
        --allow-unauthenticated -y \
        -o Dpkg::Options::='--force-confold' $*;
}

get_network() {
    API_VERSION="2008-02-01"
    METADATA_URL="http://169.254.169.254/$API_VERSION/meta-data"

    #FQDN=`hostname -f`
    FQDN=`unit-get public-address`
    PRIVATE=`unit-get private-address`
    PUBLIC=$FQDN
    HOSTNAME=`dig +short $PUBLIC`

    echo network data: $FQDN $PUBLIC $PRIVATE
}

# Workaround for: https://bugs.launchpad.net/juju/+bug/993034
echo 'Acquire::https { Proxy "false"; };' >> /etc/apt/apt.conf.d/02juju-apt-proxy

apt_get install apt-transport-https
apt_get install ntp dpkg-dev debhelper devscripts python-dev python-setuptools \
                python-support wget pwgen

get_network

# Setup a local repository and build the server if supplied in the charm
setup_local_repo || add_apt_sources
install_landscape || die "Error installing landscape"

# HTTP/HTTPS
#open-port 80/tcp
#open-port 443/tcp

exit 0
